---
name: build and deploy on cloudFront
on:
  push:
    branches: [master]

env:
  BUCKET: movieapp.asifazad799.online
  REGION: eu-north-1
  DIST_ID: E25M6XRGA3LJKV

jobs:
  deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Retrieve env file
        id: get-prod-env-file
        run: |
          env=$(aws ssm get-parameter --name movie-react-app --query 'Parameter.Value' --output text)
          echo "$env" > .prod.env

      - name: Install env-cmd
        run: npm install --froce -g env-cmd

      - name: Install Dependencies
        run: |
          node --version
          npm i --force

      - name: Build Static Website
        run: npm run build:prod

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws s3 sync --delete dist/ s3://${{ env.BUCKET }}

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/*"
